PersonalOrg/force-app/main/default/objects/Account/fields/Account_Activation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Activation_Summary__c</fullName>
    <label>Account Activation Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PersonalOrg/force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

PersonalOrg/force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
	public static void afterInsert(List<Account> newAccList)
    {
        List<Account> accList = new List<Account>();
        for(Account acc : newAccList)
        {
            if(acc.type == 'Customer' && acc.Active_Account__c==true && acc.Account_Activation_Summary__c == null)
            {
                acc.addError('Account Activation Summary Can\'t be blank When Account is Active');
            }
            if(acc.type == 'Customer' && acc.Active_Account__c==true)
            {
				accList.add(acc);
            }
        }
        if(!accList.isEmpty())
        {
            AccountTriggerHelper.createContactRecord(accList);
        }
    }
    public static void afterUpdate(List<Account> newAccList,Map<id, Account> oldAccountMap)
    {
        List<Account> accList = new List<Account>();
        for(Account acc : newAccList)
        {
            if(acc.type == 'Customer' && (oldAccountMap.get(acc.Id).Active_Account__c!=acc.Active_Account__c && acc.Active_Account__c==true) && acc.Account_Activation_Summary__c != null)
            {
				accList.add(acc);
            }
        }
        if(!accList.isEmpty())
        {
            AccountTriggerHelper.createContactRecord(accList);
        }
    }
}