PersonalOrg/force-app/main/default/objects/Account/fields/Account_Activation_Summary__c.field-meta.xml
<CustomField>
    <fullName>Account_Activation_Summary__c</fullName>
    <label>Account Activation Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

PersonalOrg/force-app/main/default/objects/Account/fields/Active_Account__c.field-meta.xml
<CustomField>
    <fullName>Active_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active Account</label>
    <type>Checkbox</type>
</CustomField>

PersonalOrg/force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
    @isTest 
    static void testAfterInsertErrorScenario() {
            Account acc = new Account(Name='Test Account 1', Type='Customer', Active_Account__c=true);
            Test.startTest();
        	Database.SaveResult result = Database.insert(acc, false);
            Test.stopTest();
            
            System.assert(!result.isSuccess());
            System.assertEquals('Account Activation Summary Can\'t be blank When Account is Active', result.getErrors()[0].getMessage());
        }

    @isTest 
    static void testAfterInsertCreateContactScenario() {
        Account acc = new Account(Name='Test Account 2', Type='Customer', Active_Account__c=true, Account_Activation_Summary__c='Test Summary');
        Test.startTest();
        insert acc;
        Test.stopTest();
        List<Contact> relatedContacts = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];
        System.assertEquals(1, relatedContacts.size(), 'Contact Record Should Be Created');
    }

    @isTest 
    static void testAfterUpdateScenario() {
        Account acc = new Account(Name='Test Account 3', Type='Customer', Active_Account__c=false);
        insert acc;
        
        acc.Active_Account__c = true;
        acc.Account_Activation_Summary__c='Test Summary';
        Test.startTest();
        update acc;
        Test.stopTest();

        List<Contact> relatedContacts = [SELECT Id FROM Contact WHERE AccountId = :acc.Id];
        System.assertEquals(1, relatedContacts.size(), 'Contact Record Should Be Created');
    }
}